import type { ContactPageCopy, SitePageCopy } from "@/types";

export const defaultContactCopy: ContactPageCopy = {
  title: "Entre em Contato",
  introduction: "Estamos aqui para ajudar você a planejar a experiência perfeita",
  detailsTitle: "Informações de Contato",
  phoneLabel: "Telefone",
  whatsappLabel: "WhatsApp",
  whatsappFallback: "Atendimento direto",
  whatsappButton: "Chamar no WhatsApp",
  emailLabel: "E-mail",
  addressLabel: "Endereço",
  hoursTitle: "Horário de Atendimento",
  weekdayHours: "Segunda a Sexta: 9h às 18h",
  saturdayHours: "Sábado: 9h às 14h",
  sundayHours: "Domingo: Fechado",
  formTitle: "Envie uma Mensagem",
  successGreeting: "Recebemos seus dados,",
  successInstructions: "Falta um passo: toque no botão abaixo para abrir o WhatsApp com sua mensagem já preenchida.",
  successPopupHint: "Se a janela não abrir sozinha, o botão resolve.",
  successButton: "Abrir conversa no WhatsApp",
  nameLabel: "Nome Completo",
  namePlaceholder: "Seu nome",
  emailFormLabel: "E-mail",
  emailPlaceholder: "seu@email.com",
  phoneFormLabel: "Telefone",
  phonePlaceholder: "(85) 99999-9999",
  messageLabel: "Mensagem",
  messagePlaceholder: "Como podemos ajudar você?",
  submitButton: "Enviar e abrir o WhatsApp",
  submittingButton: "Enviando...",
  whatsappGreeting: "Olá! Vim pelo site da Transfer Fortaleza Tur e gostaria de falar com vocês.",
  submitError: "Não foi possível enviar agora. Fale com a gente pelo WhatsApp enquanto isso.",
};

export const defaultPublicPageCopy: Record<
  "home" | "tours" | "transfers" | "packages" | "blog" | "testimonials" | "faq" | "tourDetails" | "transferDetails" | "privacy" | "cookie",
  SitePageCopy
> = {
  home: {
    heroTitle: "Passeios e Transfers em Fortaleza e Região",
    heroSubtitle: "Reserve experiências únicas em Fortaleza e região.",
    toursSectionTitle: "Transfers e Passeios mais procurados",
    destinationsBadge: "Destinos em Destaque",
    toursSectionIntro: "Transfers e Passeios saindo de Fortaleza exclusivos e organizados por categoria para transformar sua viagem em uma experiência única.",
    toursTitle: "Nossos Passeios",
    toursIntro: "Descubra experiências únicas e memoráveis com nossos passeios cuidadosamente selecionados",
    toursButton: "Ver Todos os Passeios",
    toursImagePlaceholder: "Sem imagem",
    toursDurationFallback: "Consulte",
    toursGroupLabel: "Gr pequenos",
    tourFeaturedBadge: "Destaque",
    tourReserveButton: "Reservar pelo WhatsApp",
    tourDetailsButton: "Ver passeio",
    moreToursTitle: "Mais Passeios",
    moreToursIntro: "Explore outros roteiros para encontrar a experiência ideal para sua viagem",
    transfersTitle: "Serviços de Transfer",
    transfersIntro: "Conforto e segurança em seus deslocamentos com nossa frota moderna",
    transfersButton: "Ver Todos os Transfers",
    transfersImagePlaceholder: "Sem imagem",
    transfersVehicleFallback: "Consulte",
    transfersCapacityFallback: "Consulte",
    transfersCapacitySuffix: "pessoas",
    transferDetailsButton: "Ver transfer",
    transferWhatsappButton: "WhatsApp",
    homeRelatedTitle: "Outros transfers recomendados",
    homeRelatedIntro: "Confira outras opções de transporte para sua viagem",
    homeRelatedSeeAll: "Ver todos",
    homeRelatedCardButton: "Ver transfer",
    blogTitle: "Nosso Blog",
    blogIntro: "Dicas de viagem, destinos e muito mais",
    blogButton: "Ver Todos os Artigos",
    testimonialsTitle: "O Que Nossos Clientes Dizem",
    testimonialsIntro: "Histórias reais de experiências memoráveis",
    faqTitle: "Perguntas Frequentes",
    faqIntro: "Tire suas dúvidas sobre nossos serviços",
  },
  tours: {
    title: "Nossos Passeios",
    intro: "Descubra experiências únicas e memoráveis com nossos passeios cuidadosamente selecionados",
    disabledTitle: "Seção Indisponível",
    disabledMessage: "A seção de passeios está temporariamente desativada.",
    searchPlaceholder: "Buscar passeios...",
    filtersButton: "Filtros",
    durationFilterLabel: "Duração",
    anyDuration: "Todas",
    shortDuration: "Até 1 dia",
    mediumDuration: "1-3 dias",
    longDuration: "Mais de 3 dias",
    featuredOnly: "Apenas Destaques",
    foundSingular: "passeio encontrado",
    foundPlural: "passeios encontrados",
    loadError: "Não foi possível carregar os passeios.",
    noResults: "Nenhum passeio encontrado com os filtros selecionados.",
    clearFilters: "Limpar filtros",
    imagePlaceholder: "Sem imagem",
    durationFallback: "Consulte",
    groupLabel: "Grupos pequenos",
    detailsButton: "Ver passeio",
    seoTitle: "Passeios em Fortaleza e Ceará | Transfer Fortaleza Tur",
    seoDescription: "Encontre passeios turísticos em Fortaleza e no Ceará, com roteiros para praias, dunas e destinos inesquecíveis. Consulte disponibilidade e reserve pelo WhatsApp.",
  },
  transfers: {
    title: "Serviços de Transfer",
    intro: "Conforto e segurança em seus deslocamentos com nossa frota moderna",
    disabledMessage: "A seção de transfer está temporariamente desativada.",
    searchPlaceholder: "Buscar transfers...",
    foundSingular: "transfer encontrado",
    foundPlural: "transfers encontrados",
    loadError: "Não foi possível carregar os transfers agora. Tente novamente mais tarde.",
    noResults: "Nenhum transfer encontrado com os filtros selecionados.",
    clearFilters: "Limpar filtros",
    imagePlaceholder: "Sem imagem",
    vehicleFallback: "Consulte",
    capacitySuffix: "pessoas",
    capacityFallback: "Consulte",
    detailsButton: "Ver transfer",
    seoTitle: "Transfer em Fortaleza e Ceará | Transfer Fortaleza Tur",
    seoDescription: "Reserve transfer em Fortaleza e região com conforto e segurança. Transporte para aeroporto, hotéis e destinos turísticos do Ceará.",
  },
  packages: {
    title: "Passeios e Transfers",
    intro: "Encontre passeios para conhecer Fortaleza e região, além de transfers para viajar com conforto.",
    toursTitle: "Passeios",
    toursIntro: "Experiências para descobrir Fortaleza e os destinos do Ceará.",
    transfersTitle: "Transfers",
    transfersIntro: "Transporte confortável para seus deslocamentos em Fortaleza e região.",
    seeTours: "Ver todos os passeios",
    seeTransfers: "Ver todos os transfers",
    noTours: "Nenhum passeio disponível no momento.",
    noTransfers: "Nenhum transfer disponível no momento.",
    unavailable: "Os passeios e transfers estão temporariamente indisponíveis.",
    loadError: "Não foi possível carregar os passeios e transfers agora. Tente novamente mais tarde.",
    imagePlaceholder: "Sem imagem",
    durationFallback: "Consulte",
    groupLabel: "Grupos pequenos",
    vehicleFallback: "Consulte",
    capacitySuffix: "pessoas",
    capacityFallback: "Consulte",
    seoTitle: "Passeios e Transfers em Fortaleza",
    seoDescription: "Explore passeios e transfers em Fortaleza e região. Encontre experiências, transporte e reserve sua próxima viagem.",
  },
  blog: {
    title: "Blog",
    intro: "Dicas, guias e inspirações para suas próximas aventuras",
    noPosts: "Nenhum post publicado ainda.",
    readArticlePrefix: "Ler artigo sobre",
    readTimeSuffix: "min de leitura",
    imagePlaceholder: "Transfer Fortaleza Tur",
    emptyImageAlt: "Artigo sobre turismo em Fortaleza",
    seoTitle: "Blog de Turismo em Fortaleza e Ceará",
    seoDescription: "Dicas de turismo, praias, passeios e destinos no Ceará para planejar sua próxima viagem com a Transfer Fortaleza Tur.",
  },
  testimonials: {
    title: "O Que Nossos Clientes Dizem",
    intro: "Histórias reais de experiências memoráveis",
    imagePlaceholder: "Sem foto",
  },
  faq: {
    title: "Perguntas Frequentes",
    intro: "Tire suas dúvidas sobre nossos serviços",
    noItems: "Nenhuma pergunta disponível no momento.",
  },
  tourDetails: {
    backLink: "← Voltar para passeios",
    availability: "Disponível para reserva",
    featured: "Mais vendido",
    groupLabel: "Grupo pequeno",
    urgencyTitle: "Últimas vagas disponíveis",
    urgencyText: "Reserve agora para garantir sua vaga neste passeio exclusivo.",
    aboutTitle: "Sobre este passeio",
    fullDescription: "Ler descrição completa",
    includesTitle: "O que está incluído",
    excludesTitle: "O que não está incluído",
    faqTitle: "Perguntas Frequentes",
    trust1Title: "Garantia de Satisfação",
    trust1Description: "Se não gostar, devolvemos seu dinheiro",
    trust2Title: "Pagamento Seguro",
    trust2Description: "Ambiente criptografado e protegido",
    trust3Title: "Suporte 24h",
    trust3Description: "Atendimento via WhatsApp a qualquer hora",
    trust4Title: "Empresa CNPJ Ativo",
    trust4Description: "Turismo legal e confiável",
    relatedTitle: "Quem viu este passeio também gostou",
    relatedIntro: "Descubra mais experiências incríveis em Fortaleza e região",
    relatedSeeAll: "Ver todos",
    relatedCardButton: "Ver passeio",
    durationFallback: "Consulte",
  },
  transferDetails: {
    backLink: "← Voltar para transfer",
    availability: "Disponível para orçamento",
    featured: "Destaque",
    vehicleLabel: "Veículo",
    capacityLabel: "Capacidade",
    capacitySuffix: "pessoas",
    aboutTitle: "Sobre este transfer",
    fullDescription: "Ver roteiro e detalhes do transfer",
    quoteButton: "Solicitar orçamento pelo WhatsApp",
    contactButton: "Fale conosco",
    includesTitle: "O que está incluído",
    excludesTitle: "O que não está incluído",
    faqTitle: "Perguntas sobre este transfer",
    relatedTitle: "Outros transfers recomendados",
    relatedIntro: "Confira outras opções de transporte para sua viagem",
    relatedSeeAll: "Ver todos",
    relatedCardButton: "Ver transfer",
  },
  privacy: {
    brandLabel: "Transfer Fortaleza Tur",
    title: "Política de Privacidade",
    updatedLabel: "Última atualização",
    updatedDate: "15 de setembro de 2026",
    section1Title: "1. Quais dados podem ser coletados",
    section1First: "Quando você autoriza o uso de cookies, podemos registrar informações de navegação e origem do contato, como o código do clique do anúncio (gclid), parâmetros de campanha (utm), página de entrada, data e hora, navegador e um código de referência do atendimento.",
    section1Second: "Ao clicar em um botão de WhatsApp, o código de referência pode ser incluído na mensagem preparada para facilitar a identificação do atendimento. A mensagem não é enviada automaticamente pelo site.",
    section2Title: "2. Para que usamos esses dados",
    section2Body: "Usamos essas informações para melhorar a experiência de atendimento, identificar a origem dos contatos, medir o desempenho das campanhas e entender quais páginas geram interesse. O código de referência também ajuda nossa equipe a localizar o atendimento relacionado ao contato.",
    section3Title: "3. Compartilhamento e armazenamento",
    section3Body: "Os dados podem ser processados pelos serviços necessários para funcionamento do site, registro dos leads, atendimento e medição de campanhas, incluindo Google Ads, Google Analytics 4 via Google Tag Manager ou gtag.js e, quando configurado, Meta Pixel. Essas ferramentas só são carregadas após o consentimento. Também usamos serviços de infraestrutura necessários ao funcionamento da Transfer Fortaleza Tur. Não vendemos esses dados.",
    section4Title: "4. Suas escolhas",
    section4Body: "Você pode recusar o consentimento no aviso de cookies. O WhatsApp continuará disponível, mas o site não registrará os dados de rastreamento de campanha nem adicionará o código de referência à mensagem. Você também pode apagar os dados locais do navegador a qualquer momento.",
    section5Title: "5. Contato",
    section5Body: "Para dúvidas ou solicitações relacionadas a privacidade e dados pessoais, entre em contato pelos canais disponíveis na página de contato da Transfer Fortaleza Tur.",
    seoTitle: "Política de Privacidade | Transfer Fortaleza Tur",
    seoDescription: "Saiba como a Transfer Fortaleza Tur coleta e utiliza dados de navegação e atendimento.",
  },
  cookie: {
    title: "Podemos melhorar seu atendimento?",
    message: "Com sua autorização, usamos cookies e dados de navegação para facilitar seu atendimento. Isso ajuda a abrir o WhatsApp com seu código de referência e não envia mensagens em seu nome.",
    refusalMessage: "Você pode recusar. Nesse caso, o WhatsApp continuará funcionando, mas sem o código de referência.",
    privacyLink: "Saiba quais dados são coletados",
    rejectButton: "Recusar",
    acceptButton: "Aceitar",
  },
};
