import type { ContactPageCopy } from "@/types";

export const defaultContactCopy: ContactPageCopy = {
  title: "Entre em Contato",
  introduction: "Estamos aqui para ajudar você a planejar a experiência perfeita",
  detailsTitle: "Informações de Contato",
  phoneLabel: "Telefone",
  whatsappLabel: "WhatsApp",
  whatsappFallback: "Atendimento direto",
  whatsappButton: "Chamar no WhatsApp",
  emailLabel: "E-mail",
  addressLabel: "Endereço",
  hoursTitle: "Horário de Atendimento",
  weekdayHours: "Segunda a Sexta: 9h às 18h",
  saturdayHours: "Sábado: 9h às 14h",
  sundayHours: "Domingo: Fechado",
  formTitle: "Envie uma Mensagem",
  successGreeting: "Recebemos seus dados,",
  successInstructions: "Falta um passo: toque no botão abaixo para abrir o WhatsApp com sua mensagem já preenchida.",
  successPopupHint: "Se a janela não abrir sozinha, o botão resolve.",
  successButton: "Abrir conversa no WhatsApp",
  nameLabel: "Nome Completo",
  namePlaceholder: "Seu nome",
  emailFormLabel: "E-mail",
  emailPlaceholder: "seu@email.com",
  phoneFormLabel: "Telefone",
  phonePlaceholder: "(85) 99999-9999",
  messageLabel: "Mensagem",
  messagePlaceholder: "Como podemos ajudar você?",
  submitButton: "Enviar e abrir o WhatsApp",
  submittingButton: "Enviando...",
  whatsappGreeting: "Olá! Vim pelo site da Transfer Fortaleza Tur e gostaria de falar com vocês.",
  submitError: "Não foi possível enviar agora. Fale com a gente pelo WhatsApp enquanto isso.",
};
